Name: product.rpc
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
  - 192.168.0.102:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(192.168.0.102:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
- Host: 192.168.0.102:6379
  Type: node
  Pass: "123456"